name: Skinet
channels:
  - defaults
dependencies:
  - python=3.8.8
  - pip=21.1.2
  - pip:
    - tensorflow
    - tensorboard
    - jupyter
    - matplotlib
    - numpy==1.19.5
    - opencv-python==4.5.1.48
    - ipython
    - jsonschema
    - pillow==8.1.2
    - scikit-image==0.18.1
    - scipy==1.6.2